name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Determine project changes since X days ago
      uses: ./
      id: project      
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          smtp-server: "smtp.gmail.com"
          smtp-server-port: "587"
          auth-user: ${{ secrets.EMAIL_USR }}
          auth-pass: ${{ secrets.EMAIL_PWD }}
          email-from: ${{ secrets.EMAIL_FROM }}
          recipient-emails: ${{ secrets.RECIPIENT_EMAILS }}
          project-numbers: all
          days: 1
    - name: Upload summary to artifacts
      uses: actions/upload-artifact@v1
      with:
          name: kanban
          path: kanban
